In [1]:
import pandas as pd

nav_history = pd.read_csv("../data/raw/02_nav_history.csv")
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [2]:
nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [3]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [4]:
nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [5]:
nav_history["date"] = pd.to_datetime(nav_history["date"])

nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[us]
 2   nav        46000 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 1.1 MB

In [6]:
(nav_history["nav"] <= 0).sum()

np.int64(0)

In [7]:
nav_history = nav_history.sort_values(
    ["amfi_code", "date"]
)

nav_history.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [8]:
nav_history.duplicated().sum()

np.int64(0)

In [9]:
nav_history["nav"].isnull().sum()

np.int64(0)

In [10]:
nav_history.to_csv(
    "../data/processed/02_nav_history_cleaned.csv",
    index=False
)

print("Cleaned NAV History saved successfully!")

Cleaned NAV History saved successfully!

In [11]:
investor_transactions = pd.read_csv(
    "../data/raw/08_investor_transactions.csv"
)

investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [12]:
investor_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [13]:
investor_transactions["transaction_date"] = pd.to_datetime(
    investor_transactions["transaction_date"]
)

investor_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  datetime64[us]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(9)
memory usage: 3.3 MB

In [14]:
investor_transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [15]:
(investor_transactions["amount_inr"] <= 0).sum()

np.int64(0)

In [16]:
investor_transactions["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [17]:
investor_transactions.to_csv(
    "../data/processed/08_investor_transactions_cleaned.csv",
    index=False
)

print("Investor Transactions cleaned and saved!")

Investor Transactions cleaned and saved!

In [18]:
scheme_performance = pd.read_csv(
    "../data/raw/07_scheme_performance.csv"
)

scheme_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [19]:
scheme_performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [20]:
scheme_performance[
    [
        "return_1yr_pct",
        "return_3yr_pct",
        "return_5yr_pct"
    ]
].dtypes

return_1yr_pct    float64
return_3yr_pct    float64
return_5yr_pct    float64
dtype: object

In [21]:
scheme_performance[
    (scheme_performance["expense_ratio_pct"] < 0.1)
    |
    (scheme_performance["expense_ratio_pct"] > 2.5)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [22]:
invalid_expense = scheme_performance[
    (scheme_performance["expense_ratio_pct"] < 0.1)
    |
    (scheme_performance["expense_ratio_pct"] > 2.5)
]

print("Invalid rows:", len(invalid_expense))

Invalid rows: 0

In [23]:
scheme_performance["anomaly"] = (
    scheme_performance["return_1yr_pct"] > 50
)

scheme_performance["anomaly"].value_counts()

anomaly
False    40
Name: count, dtype: int64

In [24]:
scheme_performance.to_csv(
    "../data/processed/07_scheme_performance_cleaned.csv",
    index=False
)

print("Scheme Performance cleaned and saved!")

Scheme Performance cleaned and saved!

In [25]:
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [26]:
fund_master.columns

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [27]:
import sqlite3

conn = sqlite3.connect("../bluestock_mf.db")

print("Database Created Successfully!")

Database Created Successfully!

In [28]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("../bluestock_mf.db")

print("Connected to Database")

Connected to Database

In [29]:
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [30]:
fund_master.to_sql(
    "dim_fund",
    conn,
    if_exists="replace",
    index=False
)

print("dim_fund loaded successfully!")

dim_fund loaded successfully!

In [31]:
query = "SELECT COUNT(*) FROM dim_fund"

pd.read_sql(query, conn)

   COUNT(*)
0        40

In [32]:
nav_history = pd.read_csv(
    "../data/processed/02_nav_history_cleaned.csv"
)

nav_history.head()

   amfi_code        date       nav
0     100016  2022-01-03  520.4608
1     100016  2022-01-04  515.0971
2     100016  2022-01-05  521.7239
3     100016  2022-01-06  515.7880
4     100016  2022-01-07  515.1639

In [33]:
nav_history.to_sql(
    "fact_nav",
    conn,
    if_exists="replace",
    index=False
)

print("fact_nav loaded successfully!")

fact_nav loaded successfully!

In [34]:
pd.read_sql(
    "SELECT COUNT(*) FROM fact_nav",
    conn
)

   COUNT(*)
0     46000

In [35]:
investor_transactions = pd.read_csv(
    "../data/processed/08_investor_transactions_cleaned.csv"
)

investor_transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [36]:
investor_transactions.to_sql(
    "fact_transactions",
    conn,
    if_exists="replace",
    index=False
)

print("fact_transactions loaded successfully!")

fact_transactions loaded successfully!

In [37]:
pd.read_sql(
    "SELECT COUNT(*) FROM fact_transactions",
    conn
)

   COUNT(*)
0     32778

In [38]:
scheme_performance = pd.read_csv(
    "../data/processed/07_scheme_performance_cleaned.csv"
)

scheme_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade,anomaly
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate,False
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate,False
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High,False
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High,False
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low,False

In [39]:
scheme_performance.to_sql(
    "fact_performance",
    conn,
    if_exists="replace",
    index=False
)

print("fact_performance loaded successfully!")

fact_performance loaded successfully!

In [40]:
pd.read_sql(
    "SELECT COUNT(*) FROM fact_performance",
    conn
)

   COUNT(*)
0        40

In [41]:
aum_data = pd.read_csv(
    "../data/raw/03_aum_by_fund_house.csv"
)

aum_data.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [42]:
aum_data.to_sql(
    "fact_aum",
    conn,
    if_exists="replace",
    index=False
)

print("fact_aum loaded successfully!")

fact_aum loaded successfully!

In [47]:
query = """
SELECT
    AVG(nav) AS average_nav
FROM fact_nav;
"""

pd.read_sql(query, conn)

   average_nav
0   269.570265

In [48]:
pd.read_sql("""
SELECT COUNT(*) 
FROM fact_nav;
""", conn)

   COUNT(*)
0     46000

In [49]:
pd.read_sql("""
SELECT
    transaction_type,
    COUNT(*) AS total_transactions
FROM fact_transactions
GROUP BY transaction_type;
""", conn)

  transaction_type  total_transactions
0          Lumpsum                8095
1       Redemption                4967
2              SIP               19716

In [51]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

                name
0           dim_fund
1           fact_nav
2  fact_transactions
3   fact_performance
4           fact_aum

In [53]:
pd.read_sql("""
SELECT COUNT(*) AS total_funds
FROM dim_fund;
""", conn)

   total_funds
0           40

In [54]:
pd.read_sql("""
SELECT
    transaction_type,
    COUNT(*) AS total_transactions
FROM fact_transactions
GROUP BY transaction_type;
""", conn)

  transaction_type  total_transactions
0          Lumpsum                8095
1       Redemption                4967
2              SIP               19716

In [55]:
pd.read_sql("""
SELECT
    state,
    COUNT(*) AS total_transactions
FROM fact_transactions
GROUP BY state
ORDER BY total_transactions DESC;
""", conn)

             state  total_transactions
0           Punjab                2965
1   Madhya Pradesh                2931
2       Tamil Nadu                2806
3          Gujarat                2780
4      West Bengal                2748
5          Haryana                2736
6        Telangana                2718
7    Uttar Pradesh                2695
8            Delhi                2677
9        Karnataka                2621
10       Rajasthan                2577
11     Maharashtra                2524

In [56]:
pd.read_sql("""
SELECT
    SUM(amount_inr) AS total_investment
FROM fact_transactions;
""", conn)

   total_investment
0        3521580430

In [57]:
pd.read_sql("""
SELECT
    AVG(nav) AS average_nav
FROM fact_nav;
""", conn)

   average_nav
0   269.570265

In [58]:
pd.read_sql("""
SELECT
    AVG(return_1yr_pct) AS average_return
FROM fact_performance;
""", conn)

   average_return
0          14.376

In [59]:
pd.read_sql("""
SELECT
    amfi_code,
    return_1yr_pct
FROM fact_performance
ORDER BY return_1yr_pct DESC
LIMIT 5;
""", conn)

   amfi_code  return_1yr_pct
0     101207           24.93
1     119598           24.56
2     119095           21.97
3     118634           21.30
4     119599           20.59

In [60]:
pd.read_sql("""
SELECT
    amfi_code,
    expense_ratio_pct
FROM fact_performance
WHERE expense_ratio_pct < 1;
""", conn)

    amfi_code  expense_ratio_pct
0      119552               0.66
1      119599               0.72
2      119120               0.77
3      125497               0.92
4      125498               0.78
5      100025               0.56
6      120504               0.80
7      120507               0.74
8      118633               0.72
9      118635               0.89
10     118636               0.55
11     120844               0.60
12     119093               0.75
13     101208               0.79

In [61]:
pd.read_sql("""
SELECT
    amfi_code,
    expense_ratio_pct
FROM fact_performance
WHERE expense_ratio_pct < 1;
""", conn)

    amfi_code  expense_ratio_pct
0      119552               0.66
1      119599               0.72
2      119120               0.77
3      125497               0.92
4      125498               0.78
5      100025               0.56
6      120504               0.80
7      120507               0.74
8      118633               0.72
9      118635               0.89
10     118636               0.55
11     120844               0.60
12     119093               0.75
13     101208               0.79

In [2]:
import os

print(os.getcwd())

c:\Users\mugil\Desktop\Bluestock_mf_capstone\notebooks

In [3]:
from pathlib import Path

# Project root folder
BASE_DIR = Path.cwd().parent

# Raw data folder
RAW_PATH = BASE_DIR / "data" / "raw"

# Processed data folder
PROCESSED_PATH = BASE_DIR / "data" / "processed"

print("Project Folder:", BASE_DIR)
print("Raw Folder:", RAW_PATH)
print("Processed Folder:", PROCESSED_PATH)

Project Folder: c:\Users\mugil\Desktop\Bluestock_mf_capstone
Raw Folder: c:\Users\mugil\Desktop\Bluestock_mf_capstone\data\raw
Processed Folder: c:\Users\mugil\Desktop\Bluestock_mf_capstone\data\processed

In [4]:
import pandas as pd

df = pd.read_csv(RAW_PATH / "01_fund_master.csv")

print(df.head())

   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

In [5]:
import pandas as pd

df = pd.read_csv(RAW_PATH / "01_fund_master.csv")

print("Original Shape:", df.shape)

# Remove duplicates
df = df.drop_duplicates()

# AMFI code as string
df["amfi_code"] = df["amfi_code"].astype(str)

# Convert date
df["launch_date"] = pd.to_datetime(
    df["launch_date"],
    errors="coerce"
)

# Clean text columns
text_cols = [
    "fund_house",
    "scheme_name",
    "category",
    "sub_category",
    "plan",
    "benchmark",
    "fund_manager",
    "risk_category",
    "sebi_category_code"
]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

# Save cleaned file
df.to_csv(
    PROCESSED_PATH / "01_fund_master_cleaned.csv",
    index=False
)

print("Saved Successfully")
print(df.shape)

Original Shape: (40, 15)
Saved Successfully
(40, 15)

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv(RAW_PATH / "03_aum_by_fund_house.csv")

print("Original Shape:", df.shape)

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Convert date column
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

# 3. Clean fund house names
df["fund_house"] = (
    df["fund_house"]
    .astype(str)
    .str.strip()
)

# 4. Validate AUM values
invalid_aum = df[
    (df["aum_lakh_crore"] <= 0) |
    (df["aum_crore"] <= 0)
]

print("Invalid AUM Records:", len(invalid_aum))

# 5. Validate scheme counts
invalid_schemes = df[
    df["num_schemes"] <= 0
]

print("Invalid Scheme Counts:", len(invalid_schemes))

# 6. Sort data
df = df.sort_values(
    by=["fund_house", "date"]
)

# 7. Save cleaned file
df.to_csv(
    PROCESSED_PATH / "03_aum_by_fund_house_cleaned.csv",
    index=False
)

print("Cleaned Shape:", df.shape)
print("Saved Successfully")

Original Shape: (90, 5)
Invalid AUM Records: 0
Invalid Scheme Counts: 0
Cleaned Shape: (90, 5)
Saved Successfully

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv(RAW_PATH / "04_monthly_sip_inflows.csv")

print("Original Shape:", df.shape)

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Convert month column
df["month"] = pd.to_datetime(
    df["month"],
    format="%Y-%m",
    errors="coerce"
)

# 3. Validate numeric columns
numeric_cols = [
    "sip_inflow_crore",
    "active_sip_accounts_crore",
    "new_sip_accounts_lakh",
    "sip_aum_lakh_crore"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

# 4. Fill YoY Growth Nulls
df["yoy_growth_pct"] = (
    df["yoy_growth_pct"]
    .fillna(0)
)

# 5. Validate values
invalid_rows = df[
    (df["sip_inflow_crore"] <= 0) |
    (df["active_sip_accounts_crore"] <= 0) |
    (df["new_sip_accounts_lakh"] <= 0)
]

print("Invalid Records:", len(invalid_rows))

# 6. Sort by month
df = df.sort_values("month")

# 7. Save cleaned file
df.to_csv(
    PROCESSED_PATH / "04_monthly_sip_inflows_cleaned.csv",
    index=False
)

print("Cleaned Shape:", df.shape)
print("Saved Successfully")

Original Shape: (48, 6)
Invalid Records: 0
Cleaned Shape: (48, 6)
Saved Successfully

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv(RAW_PATH / "05_category_inflows.csv")

print("Original Shape:", df.shape)

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Convert month column
df["month"] = pd.to_datetime(
    df["month"],
    format="%Y-%m",
    errors="coerce"
)

# 3. Clean category names
df["category"] = (
    df["category"]
    .astype(str)
    .str.strip()
)

# 4. Convert inflow to numeric
df["net_inflow_crore"] = pd.to_numeric(
    df["net_inflow_crore"],
    errors="coerce"
)

# 5. Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# 6. Sort data
df = df.sort_values(
    by=["month", "category"]
)

# 7. Save cleaned file
df.to_csv(
    PROCESSED_PATH / "05_category_inflows_cleaned.csv",
    index=False
)

print("\nCleaned Shape:", df.shape)
print("Saved Successfully")

Original Shape: (144, 3)

Missing Values:
month               0
category            0
net_inflow_crore    0
dtype: int64

Cleaned Shape: (144, 3)
Saved Successfully

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv(RAW_PATH / "06_industry_folio_count.csv")

print("Original Shape:", df.shape)

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Convert month column
df["month"] = pd.to_datetime(
    df["month"],
    format="%Y-%m",
    errors="coerce"
)

# 3. Convert folio columns
folio_cols = [
    "total_folios_crore",
    "equity_folios_crore",
    "debt_folios_crore",
    "hybrid_folios_crore",
    "others_folios_crore"
]

for col in folio_cols:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

# 4. Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# 5. Validate folio values
invalid_rows = df[
    (df["total_folios_crore"] <= 0)
]

print("\nInvalid Records:", len(invalid_rows))

# 6. Sort data
df = df.sort_values("month")

# 7. Save cleaned file
df.to_csv(
    PROCESSED_PATH / "06_industry_folio_count_cleaned.csv",
    index=False
)

print("\nCleaned Shape:", df.shape)
print("Saved Successfully")

Original Shape: (21, 6)

Missing Values:
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

Invalid Records: 0

Cleaned Shape: (21, 6)
Saved Successfully

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv(RAW_PATH / "09_portfolio_holdings.csv")

print("Original Shape:", df.shape)

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Convert AMFI code
df["amfi_code"] = df["amfi_code"].astype(str)

# 3. Convert portfolio date
df["portfolio_date"] = pd.to_datetime(
    df["portfolio_date"],
    errors="coerce"
)

# 4. Clean text columns
text_cols = [
    "stock_symbol",
    "stock_name",
    "sector"
]

for col in text_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.upper()
    )

# 5. Convert numeric columns
numeric_cols = [
    "weight_pct",
    "market_value_cr",
    "current_price_inr"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

# 6. Validate values
invalid_rows = df[
    (df["weight_pct"] <= 0) |
    (df["market_value_cr"] <= 0) |
    (df["current_price_inr"] <= 0)
]

print("Invalid Records:", len(invalid_rows))

# 7. Sort data
df = df.sort_values(
    by=["amfi_code", "weight_pct"],
    ascending=[True, False]
)

# 8. Save cleaned file
df.to_csv(
    PROCESSED_PATH / "09_portfolio_holdings_cleaned.csv",
    index=False
)

print("Cleaned Shape:", df.shape)
print("Saved Successfully")

Original Shape: (322, 8)
Invalid Records: 0
Cleaned Shape: (322, 8)
Saved Successfully

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv(RAW_PATH / "10_benchmark_indices.csv")

print("Original Shape:", df.shape)

# 1. Remove duplicates
df = df.drop_duplicates()

# 2. Convert date column
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

# 3. Clean index names
df["index_name"] = (
    df["index_name"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# 4. Convert close value
df["close_value"] = pd.to_numeric(
    df["close_value"],
    errors="coerce"
)

# 5. Validate values
invalid_rows = df[
    df["close_value"] <= 0
]

print("Invalid Records:", len(invalid_rows))

# 6. Sort data
df = df.sort_values(
    by=["index_name", "date"]
)

# 7. Save cleaned file
df.to_csv(
    PROCESSED_PATH / "10_benchmark_indices_cleaned.csv",
    index=False
)

print("Cleaned Shape:", df.shape)
print("Saved Successfully")

Original Shape: (8050, 3)
Invalid Records: 0
Cleaned Shape: (8050, 3)
Saved Successfully

# Day 2 - Data Cleaning & Database Preparation

## Purpose
This notebook focuses on improving data quality and preparing the dataset for database storage and analysis.

## Tasks Performed
- Handled missing values
- Removed duplicate records
- Standardized column formats
- Corrected inconsistent entries
- Prepared clean dataset for database loading

## Output
- Cleaned mutual fund dataset
- Improved data consistency and quality
- Dataset ready for SQLite integration